development:
  host: localhost
  database: landingpage_development

test:
  host: localhost
  database: landingpage_test

# set these environment variables on your prod server
production:
  uri:  mongodb://landingpage:123456@staff.mongohq.com:10050/app2666734
  #host: <%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  #datamongodb://landingpage:123456@staff.mongohq.com:10050/app2666734base: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
